[package]
name = "iterate"
version = "0.1.0"
edition = "2021"
description = "Macros for iterate struct"
license-file = "LICENSE.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
